name: template build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ '*' ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: my-bevy-game
    steps:
      - uses: actions/checkout@v2
      - uses: cargo-generate/cargo-generate-action@v0.10.1
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: template
          other: "-d wasm=true"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: move project
        run: |
          mv my-bevy-game ${{ runner.temp }}/

      - name: build project
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          cd ${{ runner.temp }}/my-bevy-game
          cargo build --release

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{ runner.temp }}/my-bevy-game
          target-dir: ${{ runner.temp }}/my-bevy-game/target
          cache-on-failure: true
